services:
  crypto-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-trading-api
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      # Server config
      - PORT=8080
      - GIN_MODE=release

      # API Security
      - API_KEY=${API_KEY}

      # Binance API
      - BINANCE_TESTNET=${BINANCE_TESTNET:-false}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}

      # Firebase config
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_CREDENTIALS_FILE=/app/config/firebase-credentials.json

      # Timezone
      - TZ=Asia/Bangkok

    volumes:
      - ./config/firebase-credentials.json:/app/config/firebase-credentials.json:ro
      - ./logs:/app/logs

    networks:
      web-net:
        aliases:
          - crypto-trading-api

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  web-net:
    external: true
